### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by HappyColour** [fex-team/yog2-kernel#87]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.<anonymous> (/data/nodejs/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.Module._load (/data/shop-i18n/clientServer/node_modules/_yog2-kernel@1.9.2@yog2-kernel/plugins/isomorphic/index.js:41:20)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/shop-i18n/clientServer/node_modules/_debug@4.1.0@debug/src/index.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.<anonymous> (/data/nodejs/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.Module._load (/data/shop-i18n/clientServer/node_modules/_yog2-kernel@1.9.2@yog2-kernel/plugins/isomorphic/index.js:41:20)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/shop-i18n/clientServer/node_modules/_i18n@0.8.3@i18n/i18n.js:16:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[root@frankfurt-motor clientServer]# ls /data/shop-i18n/clientServer/node_modules/_yog2-kernel@1.9.2@yog2-kernel/plugins/isomorphic/index.js

**Comment by HappyColour** [comment]
node version is 6.17.0
